steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gemini-fullstack-langgraph:$COMMIT_SHA', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-fullstack-langgraph:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gemini-fullstack-langgraph'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gemini-fullstack-langgraph:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},LANGSMITH_API_KEY=${_LANGSMITH_API_KEY},REDIS_URI=${_REDIS_URI},POSTGRES_URI=${_POSTGRES_URI}'

# Timeout for the entire build
timeout: '1200s'

# Make images available to Cloud Run
images:
  - 'gcr.io/$PROJECT_ID/gemini-fullstack-langgraph:$COMMIT_SHA'

# Substitutions for environment variables
substitutions:
  _GEMINI_API_KEY: ''
  _LANGSMITH_API_KEY: ''
  _REDIS_URI: ''
  _POSTGRES_URI: ''

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 